### ISSUE TITLE
Question about offset parameter in paper

### ISSUE THREAD

**Issue by agoncharenko1992** [itayhubara/CalibTIP#6]
Hi there!

In your paper https://arxiv.org/abs/2006.10518 there is a parameter V which was added to the weights of some layer in formula (2) or (3) and which should be optimized to minimize MSE between original and quantized outputs.

However, I can't find this offset parameter in your current repo. Is there something I have missed or you have decided to remove this parameter?

**Comment by itayhubara** [comment]
I optimize the weights directly starting from the float version, equivalent to optimizing V when W is fixed.

**Comment by agoncharenko1992** [comment]
ok, thanks!
